### ISSUE TITLE
Clarification about calc_word_bool 

### ISSUE THREAD

**Issue by rfm-targa** [aziele/alfpy#1]
Good night,

I'm using the alfpy package through the command line and I'm currently using the script calc_word_bool.py because I'm interest in getting the distance matrices for sequences in fasta files. I automated the process so that I can get a lot of results with different measures but every measure gives the same result.
Using 'dice', 'hamming' or 'jaccard' with word_size 4 or any other word size just gives the same results when comparing different measures with same word_size. Is it normal for different measures to not show any difference? The word_size is the same but I was expecting the results to vary a little since the measure isn't the same.
I've looked into the python script of calc_word_bool.py and it seems that the measure chosen by the user isn't passed and that the script always uses 'jaccard'. I'm not sure but maybe someone could look into that, please.
This package can really help with some tasks so I was looking into using it but I really need to know if the results shouldn't be different.

Best regards

**Comment by aziele** [comment]
Thank you for reporting this issue. You are right, the distance measure chosen by the user wasn't passed to further calculations. As a result, all distance measures handle by the `calc_word_bool` script returned the same results. I've just fixed this issue and updated the repository. Sorry for the inconvenience.
